CITIES_TO_SUBJECTS = {'ABAKAN': 'Республика Хакасия',
 "ARHANGEL'SK":'Архангельская область',
 "ASTRAHAN'":'Астраханская область',
 'BARNAUL':'Алтайский край',
 'BELGOROD':'Белгородская область',
 'BIROBIDZHAN':'Еврейская автономная область',
 'BLAGOVESHENSK':'Амурская область',
 'BRYANSK':'Брянская область',
 'CHEBOKSARI':'Чувашская Республика - Чувашия',
 'CHELYABINSK-GOROD':'Челябинская область',
 'CHERKESSK':'Карачаево-Черкесская Республика',
 'CHITA':'Забайкальский край',
 'EKATERINBURG':'Свердловская область',
 'ELISTA':'Республика Калмыкия',
 'GORNO-ALTAJSK':'Республика Алтай',
 'GROZNIJ':'Чеченская Республика',
 'HABAROVSK':'Хабаровский край',
 'HANTY-MANSIJSK':'Ханты-Мансийский автономный округ - Югра',
 'IRKUTSK':'Иркутская область',
 'IVANOVO':'Ивановская область',
 'IZHEVSK':'Удмуртская Республика',
 'JAKUTSK':'Республика Саха (Якутия)',
 "JAROSLAVL'":'Ярославская область',
 'JOSHKAR-OLA':'Республика Марий Эл',
 'KALININGRAD':'Калининградская область',
 'KALUGA':'Калужская область',
 "KAZAN'":'Республика Татарстан (Татарстан)',
 'KEMEROVO':'Кемеровская область',
 'KIROV':'Кировская область',
 'KIZIL':'Республика Тыва',
 'KOSTROMA':'Костромская область',
 'KRASNODAR':'Краснодарский край',
 'KRASNOJARSK OPYTNOE POLE':'Красноярский край',
 'KURGAN':'Курганская область',
 'KURSK':'Курская область',
 'LIPECK':'Липецкая область',
 'MAHACKALA':'Республика Дагестан',
 'MAJKOP':'Республика Адыгея (Адыгея)',
 'MOSKVA':'г. Москва',
 'MURMANSK': 'Мурманская область',
 "NAL'CHIK":'Кабардино-Балкарская Республика',
 "NAZRAN'":'Республика Ингушетия',
 'NIZNIJ NOVGOROD':'Нижегородская область',
 'NOVGOROD':'Новгородская область',
 'NOVOSIBIRSK':'Новосибирская область',
 'OMSK':'Омская область',
 'OREL':'Орловская область',
 'ORENBURG':'Оренбургская область',
 'PENZA':'Пензенская область',
 "PERM'":'Пермский край',
 'PETROZAVODSK':'Республика Хакасия',
 'PSKOV':'Псковская область',
 "RJAZAN'":'Рязанская область',
 'ROSTOV-NA-DONU':'Ростовская область',
 'SALEHARD':'Ямало-Ненецкий автономный округ',
 'SAMARA':'Самарская область',
 'SARANSK':'Республика Мордовия',
 'SARATOV':'Саратовская область',
 "SIMFEROPOL'":'Автономная Республика Крым',
 'SMOLENSK':'Смоленская область',
 'ST.PETERSBURG':'Ленинградская область',
 "STAVROPOL'":'Ставропольский край',
 'SYKTYVKAR':'Республика Коми',
 'TAMBOV':'Тамбовская область',
 "TJUMEN'":'Тюменская область',
 'TOMSK':'Томская область',
 'TULA':'Тульская область',
 "TVER'":'Тверская область',
 'UFA':'Республика Башкортостан',
 "UL'YANOVSK":'Ульяновская область',
 'ULAN-UDE':'Республика Бурятия',
 'VLADIMIR':'Владимирская область',
 'VLADIVOSTOK':'Приморский край',
 'VOLGOGRAD':'Волгоградская область',
 'VOLOGDA':'Вологодская область',
 'VORONEZ':'Воронежская область',
 'WLADIKAVKAZ':'Республика Северная Осетия - Алания'}



#%%
SUBJECTS_TO_CITIES = {}
for k, v in CITIES_TO_SUBJECTS.items():
    if v != "":
        SUBJECTS_TO_CITIES[v] = k

SUBJECTS_TO_CITIES['Московская область'] = 'MOSKVA'
SUBJECTS_TO_CITIES['г. Санкт-Петербург'] = 'ST.PETERSBURG'


CITIES_TO_ID = {
 'ABAKAN': 'RU-KK',
 "ARHANGEL'SK":'RU-ARK',
 "ASTRAHAN'":'RU-AST',
 'BARNAUL':'RU-ALT',
 'BELGOROD':'RU-BEL',
 'BIROBIDZHAN':'RU-YEV',
 'BLAGOVESHENSK':'RU-AMU',
 'BRYANSK':'RU-BRY',
 'CHEBOKSARI':'RU-CU',
 'CHELYABINSK-GOROD':'RU-CHE',
 'CHERKESSK':'RU-KC',
 'CHITA':'RU-ZAB',
 'EKATERINBURG':'RU-SVE',
 'ELISTA':'RU-KL',
 'GORNO-ALTAJSK':'RU-AL',
 'GROZNIJ':'RU-CE',
 'HABAROVSK':'RU-KHA',
 'HANTY-MANSIJSK':'RU-KHM',
 'IRKUTSK':'RU-IRK',
 'IVANOVO':'RU-IVA',
 'IZHEVSK':'RU-UD',
 'JAKUTSK':'RU-SA',
 "JAROSLAVL'":'RU-YAR',
 'JOSHKAR-OLA':'RU-ME',
 'KALININGRAD':'RU-KGD',
 'KALUGA':'RU-KLU',
 "KAZAN'":'RU-TA',
 'KEMEROVO':'RU-KEM',
 'KIROV':'RU-KIR',
 'KIZIL':'RU-TY',
 'KOSTROMA':'RU-KOS',
 'KRASNODAR':'RU-KDA',
 'KRASNOJARSK OPYTNOE POLE':'RU-KYA',
 'KURGAN':'RU-KGN',
 'KURSK':'RU-KRS',
 'LIPECK':'RU-LIP',
 'MAHACKALA':'RU-DA',
 'MAJKOP':'RU-AD',
 'MOSKVA':'RU-MOW',
 'MURMANSK': 'RU-MUR',
 "NAL'CHIK":'RU-KB',
 "NAZRAN'":'RU-IN',
 'NIZNIJ NOVGOROD':'RU-NIZ',
 'NOVGOROD':'RU-NGR',
 'NOVOSIBIRSK':'RU-NVS',
 'OMSK':'RU-OMS',
 'OREL':'RU-ORL',
 'ORENBURG':'RU-ORE',
 'PENZA':'RU-PNZ',
 "PERM'":'RU-PER',
 'PETROZAVODSK':'RU-KK',
 'PSKOV':'RU-PSK',
 "RJAZAN'":'RU-RYA',
 'ROSTOV-NA-DONU':'RU-ROS',
 'SALEHARD':'RU-YAN',
 'SAMARA':'RU-SAM',
 'SARANSK':'RU-MO',
 'SARATOV':'RU-SAR',
 "SIMFEROPOL'":'RU-CR',
 'SMOLENSK':'RU-SMO',
 'ST.PETERSBURG':'RU-SPE',
 "STAVROPOL'":'RU-STA',
 'SYKTYVKAR':'RU-KO',
 'TAMBOV':'RU-TAM',
 "TJUMEN'":'RU-TYU',
 'TOMSK':'RU-TOM',
 'TULA':'RU-TUL',
 "TVER'":'RU-TVE',
 'UFA':'RU-BA',
 "UL'YANOVSK":'RU-ULY',
 'ULAN-UDE':'RU-BU',
 'VLADIMIR':'RU-VLA',
 'VLADIVOSTOK':'RU-PRI',
 'VOLGOGRAD':'RU-VGG',
 'VOLOGDA':'RU-VLG',
 'VORONEZ':'RU-VOR',
 'WLADIKAVKAZ':'RU-SE'}
