from yaweather.cities import Russia

CITIES_TO_SUBJECTS = {'ABAKAN': 'Республика Хакасия',
 "ARHANGEL'SK":'Архангельская область',
 "ASTRAHAN'":'Астраханская область',
 'BARNAUL':'Алтайский край',
 'BELGOROD':'Белгородская область',
 'BIROBIDZHAN':'Еврейская автономная область',
 'BLAGOVESHENSK':'Амурская область',
 'BRYANSK':'Брянская область',
 'CHEBOKSARI':'Чувашская Республика - Чувашия',
 'CHELYABINSK-GOROD':'Челябинская область',
 'CHERKESSK':'Карачаево-Черкесская Республика',
 'CHITA':'Забайкальский край',
 'EKATERINBURG':'Свердловская область',
 'ELISTA':'Республика Калмыкия',
 'GORNO-ALTAJSK':'Республика Алтай',
 'GROZNIJ':'Чеченская Республика',
 'HABAROVSK':'Хабаровский край',
 'HANTY-MANSIJSK':'Ханты-Мансийский автономный округ - Югра',
 'IRKUTSK':'Иркутская область',
 'IVANOVO':'Ивановская область',
 'IZHEVSK':'Удмуртская Республика',
 'JAKUTSK':'Республика Саха (Якутия)',
 "JAROSLAVL'":'Ярославская область',
 'JOSHKAR-OLA':'Республика Марий Эл',
 'KALININGRAD':'Калининградская область',
 'KALUGA':'Калужская область',
 "KAZAN'":'Республика Татарстан (Татарстан)',
 'KEMEROVO':'Кемеровская область',
 'KIROV':'Кировская область',
 'KIZIL':'Республика Тыва',
 'KOSTROMA':'Костромская область',
 'KRASNODAR':'Краснодарский край',
 'KRASNOJARSK OPYTNOE POLE':'Красноярский край',
 'KURGAN':'Курганская область',
 'KURSK':'Курская область',
 'LIPECK':'Липецкая область',
 'MAHACKALA':'Республика Дагестан',
 'MAJKOP':'Республика Адыгея (Адыгея)',
 'MOSKVA':'г. Москва',
 'MURMANSK': 'Мурманская область',
 "NAL'CHIK":'Кабардино-Балкарская Республика',
 "NAZRAN'":'Республика Ингушетия',
 'NIZNIJ NOVGOROD':'Нижегородская область',
 'NOVGOROD':'Новгородская область',
 'NOVOSIBIRSK':'Новосибирская область',
 'OMSK':'Омская область',
 'OREL':'Орловская область',
 'ORENBURG':'Оренбургская область',
 'PENZA':'Пензенская область',
 "PERM'":'Пермский край',
 'PETROZAVODSK':'Республика Хакасия',
 'PSKOV':'Псковская область',
 "RJAZAN'":'Рязанская область',
 'ROSTOV-NA-DONU':'Ростовская область',
 'SALEHARD':'Ямало-Ненецкий автономный округ',
 'SAMARA':'Самарская область',
 'SARANSK':'Республика Мордовия',
 'SARATOV':'Саратовская область',
 "SIMFEROPOL'":'Автономная Республика Крым',
 'SMOLENSK':'Смоленская область',
 'ST.PETERSBURG':'Ленинградская область',
 "STAVROPOL'":'Ставропольский край',
 'SYKTYVKAR':'Республика Коми',
 'TAMBOV':'Тамбовская область',
 "TJUMEN'":'Тюменская область',
 'TOMSK':'Томская область',
 'TULA':'Тульская область',
 "TVER'":'Тверская область',
 'UFA':'Республика Башкортостан',
 "UL'YANOVSK":'Ульяновская область',
 'ULAN-UDE':'Республика Бурятия',
 'VLADIMIR':'Владимирская область',
 'VLADIVOSTOK':'Приморский край',
 'VOLGOGRAD':'Волгоградская область',
 'VOLOGDA':'Вологодская область',
 'VORONEZ':'Воронежская область',
 'WLADIKAVKAZ':'Республика Северная Осетия - Алания'}



#%%
SUBJECTS_TO_CITIES = {}
for k, v in CITIES_TO_SUBJECTS.items():
    if v != "":
        SUBJECTS_TO_CITIES[v] = k

SUBJECTS_TO_CITIES['Московская область'] = 'MOSKVA'
SUBJECTS_TO_CITIES['г. Санкт-Петербург'] = 'ST.PETERSBURG'


CITIES_TO_ID = {
 'ABAKAN': 'RU-KK',
 "ARHANGEL'SK":'RU-ARK',
 "ASTRAHAN'":'RU-AST',
 'BARNAUL':'RU-ALT',
 'BELGOROD':'RU-BEL',
 'BIROBIDZHAN':'RU-YEV',
 'BLAGOVESHENSK':'RU-AMU',
 'BRYANSK':'RU-BRY',
 'CHEBOKSARI':'RU-CU',
 'CHELYABINSK-GOROD':'RU-CHE',
 'CHERKESSK':'RU-KC',
 'CHITA':'RU-ZAB',
 'EKATERINBURG':'RU-SVE',
 'ELISTA':'RU-KL',
 'GORNO-ALTAJSK':'RU-AL',
 'GROZNIJ':'RU-CE',
 'HABAROVSK':'RU-KHA',
 'HANTY-MANSIJSK':'RU-KHM',
 'IRKUTSK':'RU-IRK',
 'IVANOVO':'RU-IVA',
 'IZHEVSK':'RU-UD',
 'JAKUTSK':'RU-SA',
 "JAROSLAVL'":'RU-YAR',
 'JOSHKAR-OLA':'RU-ME',
 'KALININGRAD':'RU-KGD',
 'KALUGA':'RU-KLU',
 "KAZAN'":'RU-TA',
 'KEMEROVO':'RU-KEM',
 'KIROV':'RU-KIR',
 'KIZIL':'RU-TY',
 'KOSTROMA':'RU-KOS',
 'KRASNODAR':'RU-KDA',
 'KRASNOJARSK OPYTNOE POLE':'RU-KYA',
 'KURGAN':'RU-KGN',
 'KURSK':'RU-KRS',
 'LIPECK':'RU-LIP',
 'MAHACKALA':'RU-DA',
 'MAJKOP':'RU-AD',
 'MOSKVA':'RU-MOW',
 'MURMANSK': 'RU-MUR',
 "NAL'CHIK":'RU-KB',
 "NAZRAN'":'RU-IN',
 'NIZNIJ NOVGOROD':'RU-NIZ',
 'NOVGOROD':'RU-NGR',
 'NOVOSIBIRSK':'RU-NVS',
 'OMSK':'RU-OMS',
 'OREL':'RU-ORL',
 'ORENBURG':'RU-ORE',
 'PENZA':'RU-PNZ',
 "PERM'":'RU-PER',
 'PETROZAVODSK':'RU-KK',
 'PSKOV':'RU-PSK',
 "RJAZAN'":'RU-RYA',
 'ROSTOV-NA-DONU':'RU-ROS',
 'SALEHARD':'RU-YAN',
 'SAMARA':'RU-SAM',
 'SARANSK':'RU-MO',
 'SARATOV':'RU-SAR',
 "SIMFEROPOL'":'RU-CR',
 'SMOLENSK':'RU-SMO',
 'ST.PETERSBURG':'RU-SPE',
 "STAVROPOL'":'RU-STA',
 'SYKTYVKAR':'RU-KO',
 'TAMBOV':'RU-TAM',
 "TJUMEN'":'RU-TYU',
 'TOMSK':'RU-TOM',
 'TULA':'RU-TUL',
 "TVER'":'RU-TVE',
 'UFA':'RU-BA',
 "UL'YANOVSK":'RU-ULY',
 'ULAN-UDE':'RU-BU',
 'VLADIMIR':'RU-VLA',
 'VLADIVOSTOK':'RU-PRI',
 'VOLGOGRAD':'RU-VGG',
 'VOLOGDA':'RU-VLG',
 'VORONEZ':'RU-VOR',
 'WLADIKAVKAZ':'RU-SE'
}

CITY_TO_COORDS = {
'RU-KK': (61., 34),
 'RU-ARK': (64, 40),
 'RU-AST': (46, 48),
 'RU-ALT': Russia.Barnaul,
 'RU-BEL': (50, 36),
 'RU-YEV': (48, 132),
 'RU-AMU': (50, 127),
 'RU-BRY': (53, 34),
 'RU-CU': (56, 47),
 'RU-CHE': Russia.Chelyabinsk,
 'RU-KC': (44, 42),
 'RU-ZAB': (52, 113),
 'RU-SVE': Russia.Yekaterinburg,
 'RU-KL': (46, 44),
 'RU-AL': (51, 85),
 'RU-CE': (43, 45),
 'RU-KHA': Russia.Khabarovsk,
 'RU-KHM': (61, 69),
 'RU-IRK': Russia.Irkutsk,
 'RU-IVA': (57, 41),
 'RU-UD': Russia.Izhevsk,
 'RU-SA': (62, 129),
 'RU-YAR': Russia.Yaroslavl,
 'RU-ME': (56, 47),
 'RU-KGD': (54, 20),
 'RU-KLU': (54, 36),
 'RU-TA': Russia.Kazan,
 'RU-KEM': (55, 86),
 'RU-KIR': (58, 49),
 'RU-TY': (51, 94),
 'RU-KOS': (57, 40),
 'RU-KDA': Russia.Krasnodar,
 'RU-KYA': Russia.Krasnoyarsk,
 'RU-KGN': (55, 65),
 'RU-KRS': (51, 36),
 'RU-LIP': (52, 39),
 'RU-DA': Russia.Makhachkala,
 'RU-AD': (44, 40),
 'RU-MOW': Russia.Moscow,
 'RU-MUR': (68, 33),
 'RU-KB': (43, 43),
 'RU-IN': (43, 44),
 'RU-NIZ': Russia.NizhniyNovgorod,
 'RU-NGR': (58, 31),
 'RU-NVS': Russia.Novosibirsk,
 'RU-OMS': Russia.Omsk,
 'RU-ORL':(52, 36),
 'RU-ORE': Russia.Orenburg,
 'RU-PNZ': (53, 45),
 'RU-PER': Russia.Perm,
 'RU-PSK': (57, 28),
 'RU-RYA': (54, 39),
 'RU-ROS': Russia.RostovnaDonu,
 'RU-YAN': (66, 66),
 'RU-SAM': Russia.Samara,
 'RU-MO': (54, 45),
 'RU-SAR': Russia.Saratov,
 'RU-CR': (44, 34),
 'RU-SMO': (54, 32),
 'RU-SPE': Russia.SaintPetersburg,
 'RU-STA': (45, 41),
 'RU-KO': (61, 50),
 'RU-TAM': (52, 41),
 'RU-TYU': (57, 65),
 'RU-TOM': (56, 84),
 'RU-TUL': (54, 37),
 'RU-TVE': (56, 35),
 'RU-BA': Russia.Ufa,
 'RU-ULY': Russia.Ulyanovsk,
 'RU-BU': (51, 107),
 'RU-VLA': (56, 40),
 'RU-PRI': Russia.Vladivostok,
 'RU-VGG': Russia.Volgograd,
 'RU-VLG': (59, 39),
 'RU-VOR': Russia.Voronezh,
 'RU-SE': (43, 44)
}